triggers:
- description: null
  envs: []
  last_enabled_at: 2025-01-04 15:09:40.971272
  name: s3PutTrigger
  pipeline_uuid: dataprocessing
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2025-01-04 15:09:00
  status: active
  token: test
