version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: region
  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: mongodb://{{ env_var('MONGO_USER') }}:{{ env_var('MONGO_PASSWD') }}@{{ env_var('MONGO_HOST') }}:27017/?authSource=admin
  MONGODB_PORT: 27017
  MONGODB_DATABASE: database
  # Neo4j
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  NEO_CONNECTION_STRING: bolt://{{ env_var('NEO_HOST') }}:7687
  NEO_HOST: "{{ env_var('NEO_HOST') }}"
  NEO_PORT: 7687
  NEO_USER: "{{ env_var('NEO_USER') }}"
  NEO_PASSWORD: "{{ env_var('NEO_PASSWD') }}"
  NEO_DATABASE: database
