name: CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  archtype:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log into DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mage-project .

    - name: Run Docker Container
      run:  docker run -d --name mage-project ${{ secrets.DOCKER_USERNAME }}/mage-project

    - name: View Docker Logs
      run: docker logs mage-project

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mage-project:latest
